### ISSUE TITLE
Error in computing the clusters

### ISSUE THREAD

**Issue by zaidalyafeai** [ARBML/masader-webservice#22]
```
embeddings = np.asarray(embeddings)

Process refresh_globals:

TypeError: float() argument must be a string or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "/root/.nix-profile/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap

self.run()

File "/root/.nix-profile/lib/python3.8/multiprocessing/process.py", line 108, in run

self._target(*self._args, **self._kwargs)

File "/app/utils/dataset_utils.py", line 26, in refresh_masader_and_tags

clusters, reduced_embeddings = get_masader_clusters(embeddings)

File "/app/utils/clusters_utils.py", line 9, in get_masader_clusters

reduced_embeddings = compute_reduced_embeddings(embeddings)

File "/app/utils/clusters_utils.py", line 23, in compute_reduced_embeddings

tsne_data = tsne_model.fit_transform(embeddings)

File "/opt/venv/lib/python3.8/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped

data_to_wrap = f(self, X, *args, **kwargs)

File "/opt/venv/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper

return fit_method(estimator, *args, **kwargs)

File "/opt/venv/lib/python3.8/site-packages/sklearn/manifold/_t_sne.py", line 1111, in fit_transform

embedding = self._fit(X)

File "/opt/venv/lib/python3.8/site-packages/sklearn/manifold/_t_sne.py", line 841, in _fit

X = self._validate_data(

File "/opt/venv/lib/python3.8/site-packages/sklearn/base.py", line 605, in _validate_data

out = check_array(X, input_name="X", **check_params)

File "/opt/venv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 915, in check_array

array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)

File "/opt/venv/lib/python3.8/site-packages/sklearn/utils/_array_api.py", line 380, in _asarray_with_order

array = numpy.asarray(array, order=order, dtype=dtype)

ValueError: setting an array element with a sequence.
```
cc @AliOsm

**Comment by zaidalyafeai** [comment]
Extra spaces in the embeddings for some reason caused the error. Fix for now.
